language: generic
sudo : required

services: 
  - docker

before_install: 
  - docker build -t amirsha99/docker_react -f Dockerfile.dev .

script: 
  - docker run -e CI=true amirsha99/docker_react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker_react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-529438765371"
  bucket_path: "docker_react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY  
  secret_access_key:
    secure: "$AWS_SECRET_KEY"